# frozen_string_literal: true

# This file was generated by the `rspec --init` command to configure RSpec.
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rspec'
require 'json' # Include any libraries or gems that you are using in your project.

RSpec.configure do |config|
  # Enable `should` and `expect` syntaxes for writing tests.
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # Set the mock framework to use.
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Only run tests tagged with `:focus`, or all if none are tagged.
  config.filter_run_when_matching :focus

  # Stop running tests after a failure.
  config.fail_fast = true if ENV['RSPEC_FAIL_FAST']

  # Show the 10 slowest examples.
  config.profile_examples = 10

  # Randomize the order in which tests are run to expose order dependencies.
  config.order = :random

  # Seed random order to reproduce failures.
  Kernel.srand config.seed

  # Additional global settings or helper methods can be placed here.

  # Disable monkey patching of core Ruby objects.
  config.disable_monkey_patching!
end
